kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    commands:
    settings:
#     username: oscohen
#     password: nata2411
      repo: quay.io/oscohen/ignition-manifests-and-kubeconfig-generate_test
      dockerfile: Dockerfile.ignition-manifests-and-kubeconfig-generate